### ISSUE TITLE
How to create /tweets view?

### ISSUE THREAD

**Issue by thejimbirch** [backdrop-contrib/twitter#1]
Hello,

On /admin/config/services/twitter there is a message:

Tweets are pulled from Twitter by running cron. You can view the full list of tweets at the Tweets view.

The "Tweets view" is not being created, and it appears that there is no way to create it.

Tweets are being imported into my database though.

Can you advise?

Thanks,
Jim

**Comment by Graham-72** [comment]
Thanks @CaffeinatedJim for reporting this. I went and checked on a D7 site and found the same issue. Then I found this - https://www.drupal.org/node/1253026 - which I will have to check out and see how we apply it in Backdrop. It may be a few days before I do this.

**Comment by thejimbirch** [comment]
Hi @Graham-72,

When I install the Twitter module on D7, I get a view pre-built:

![screen shot 2015-03-16 at 10 57 43 am](https://cloud.githubusercontent.com/assets/5177009/6670223/73029932-cbcb-11e4-9ef6-9c98891de033.png)

**Comment by Graham-72** [comment]
Hi @CaffeinatedJim 

Yes, I get something similar on D7, though mine (which was installed some time ago) does not have the paths listed. I must try a fresh install on D7.

Do you get a page view on D7 ? - I just get the block view.

I see that the twitter module is expecting to use version 2 of the Views API whereas Backdrop provides version 3, so maybe that is why it is not getting installed in Backdrop - a mismatch somewhere.

**Comment by thejimbirch** [comment]
Yes @Graham-72, at least on this install it came with 2 page displays, /tweets, and /tweets-raw, and corresponding blocks also.  I am not saying this is needed exactly, but being able to query the tweet entities in views is the important part that is missing.

**Comment by Graham-72** [comment]
Hi @CaffeinatedJim - I have found out how one gets the views in Backdrop and the necessary changes are now in this repo. Please download and try the current set of files. The page view of tweets is now there but I need to find out how to get the block view included in the list of blocks.

**Comment by thejimbirch** [comment]
Hi @Graham-72 !
I uninstalled the old, downloaded and installed the new.  The View is created, and the Block is in my list.  It also appears in the View creation screen as an option.  Great progress!

Some things I found:

The "Twitter: Message text" field does not display in the block.

When you create your own view, this error pops up a lot, one for every tweet:
Notice: Undefined property: stdClass::$twitter_created_time in twitter_views_handler_field_formatted_tweet->render() (line 149 of .../modules/contrib/twitter/twitter_views_field_handlers.inc).

When using Radix theme, I get the following notices:
Notice: Undefined variable: classes_array in include() (line 18 of .../themes/radix/templates/view/views-view-list.tpl.php). (One for every Tweet on the page)
Notice: Array to string conversion in include() (line 30 of .../themes/radix/templates/view/views-view.tpl.php). (Just once)

Hope this helps.

Thanks,
Jim

**Comment by Graham-72** [comment]
Hi Jim,
Thank you for this detailed report. I'm sorry to have taken a while to investigate. I have now made an addition to twitter.module and have noticed an omission from core views.module and raised an issue at https://github.com/backdrop/backdrop-issues/issues/847

With these changes the Twitter module seems to behaving better but I have not yet checked it when using Radix theme.

Best regards
Graham

**Comment by thejimbirch** [comment]
Hi Graham,

I believe I need to wait until 1.0.6 is released to verify everything.  Do you think that is right?

Thanks,
Jim

**Comment by Graham-72** [comment]
Hi Jim,
I added (by hand) the necessary line to core on my server, in views.module, at line 2157 or near there

```
'views_handler_field_broken' => 'handlers/views_handler_field.inc',
```

You should then be able to carry on testing though I haven't yet verified everything.
Graham

**Comment by Graham-72** [comment]
@thejimbirch Are you finding any problems with the new release of this Twitter module?  If OK I will close this issue.

**Comment by thejimbirch** [comment]
Sorry for my absence.  I will try to look into it this weekend.

**Comment by thejimbirch** [comment]
Yes, thanks Graham
